const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
const GET_SKILLS_LOADING = "GET_SKILLS_LOADING";
const GET_SKILLS_FAILURE = "GET_SKILLS_FAILURE";

const GET_TEXT_SECTIONS_SUCCESS = "GET_TEXT_SECTIONS_SUCCESS";
const GET_TEXT_SECTIONS_FAILURE = "GET_TEXT_SECTIONS_FAILURE";
const GET_TEXT_SECTIONS_LOADING = "GET_TEXT_SECTIONS_LOADING";

const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
const GET_PROJECTS_LOADING = "GET_PROJECTS_LOADING";

const SUBMIT_CONTACT_FORM_LOADING = "SUBMIT_CONTACT_FORM_LOADING";
const SUBMIT_CONTACT_FORM_SUCCESS = "SUBMIT_CONTACT_FORM_SUCCESS";
const SUBMIT_CONTACT_FORM_FAILURE = "SUBMIT_CONTACT_FORM_FAILURE";

export {
  GET_SKILLS_SUCCESS,
  GET_SKILLS_LOADING,
  GET_SKILLS_FAILURE,
  GET_TEXT_SECTIONS_SUCCESS,
  GET_TEXT_SECTIONS_FAILURE,
  GET_TEXT_SECTIONS_LOADING,
  GET_PROJECTS_SUCCESS,
  GET_PROJECTS_FAILURE,
  GET_PROJECTS_LOADING,
  SUBMIT_CONTACT_FORM_LOADING,
  SUBMIT_CONTACT_FORM_SUCCESS,
  SUBMIT_CONTACT_FORM_FAILURE,
};
